language: python
python:
  - "2.7"

env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=pypy26
  - TOX_ENV=pep8

install:
  - "pip install tox"

script:
  - NOSE_VERBOSE=0 tox -e $TOX_ENV

sudo: false
